name: ESLint Code Analysis

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules

      - name: Install Node.js dependencies
        run: npm install

      - name: Create reports directory
        run: mkdir -p reports

      - name: Install ESLint SARIF Formatter
        run: npm install @microsoft/eslint-formatter-sarif --save-dev

      - name: Run ESLint with SARIF output
        run: |
          npx eslint . \
            --ext .js,.mjs \
            --format @microsoft/eslint-formatter-sarif \
            --output-file reports/eslint-results.sarif


      - name: Debug SARIF file
        run: |
          if [ -f reports/eslint-results.sarif ]; then
            echo "✅ SARIF generated:"
            cat reports/eslint-results.sarif
          else
            echo "❌ reports/eslint-results.sarif not found"
            exit 1
          fi

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/eslint-results.sarif