name: SonarQube Analysis

on:
  push:         { branches: [ main ] }
  pull_request: { branches: [ main ] }
  workflow_dispatch:

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:9-community
        ports: ["9000:9000"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Wait for SonarQube to be ready
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:9000/api/server/version; then
              echo "✅ SonarQube is up!"
              break
            fi
            echo "⌛ Waiting for SonarQube… ($i)"
            sleep 5
          done

      - name: Run SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          # these args go straight to sonar-scanner
          args: >
            -Dsonar.projectKey=your-project-key
            -Dsonar.sources=.
        env:
          SONAR_HOST_URL: http://localhost:9000
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
