name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarqube:
    runs-on: [self-hosted, windows, X64]

    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}      # http://localhost:9000
      SONAR_TOKEN:     ${{ secrets.SONARQUBE_TOKEN }}

    defaults:
      run:
        shell: powershell -ExecutionPolicy Bypass

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # If Node/Java/Scanner not preinstalled, keep the install steps you used before.
      # (Chocolatey Node, Temurin 17, download scanner, etc.)

      - name: Run SonarScanner
        shell: cmd 
        run: >
          sonar-scanner.bat -Dsonar.projectKey=SSD-Lab -Dsonar.sources=. -Dsonar.host.url=%SONAR_HOST_URL% -Dsonar.token=%SONAR_TOKEN%
