name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarqube:
    runs-on: [self-hosted, windows, sonar]  # match labels you set
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci

      - name: Check SonarQube connectivity
        shell: powershell
        run: |
          $resp = Invoke-WebRequest "$env:SONAR_HOST_URL/api/system/health" -UseBasicParsing
          Write-Host $resp.Content
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.3.0
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   # http://localhost:9000
          SONAR_TOKEN:     ${{ secrets.SONARQUBE_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=SSD-Lab
            -Dsonar.sources=.
