name: SonarQube Analysis

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  sonar:
    runs-on: [self-hosted]      # must match your self-hosted runner label
    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Install SonarScanner
        run: |
          curl -sSL -o scanner.zip \
            https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.1.0.4889-linux.zip
          unzip scanner.zip -d $RUNNER_TEMP
          echo "$RUNNER_TEMP/sonar-scanner-*/bin" >> $GITHUB_PATH

      - name: Run SonarQube analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your-project-key \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
