name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:                # so you can trigger manually

jobs:
  sonarqube:
    name: Analyze with SonarQube
    runs-on: [self-hosted, windows]  # ← point at your Windows self‑hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0             # gives Sonar full history for coverage, etc.

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   # should be http://localhost:9000
        with:
          args: >
            -Dsonar.projectKey=your-project-key
            -Dsonar.sources=.
