name: SonarQube Analysis

on:
  push:         { branches: [ main ] }
  pull_request: { branches: [ main ] }
  workflow_dispatch:

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:9-community
        ports: ["9000:9000"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Wait for SonarQube
        run: |
          until curl -sSf http://localhost:9000/api/server/version; do
            echo "Waiting for SonarQube…"
            sleep 5
          done

      - name: Run SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.projectKey=github-test-scan
            -Dsonar.sources=.
        env:
          SONAR_HOST_URL: http://localhost:9000
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}